### ISSUE TITLE
Check mark for secondary subtitles is too big on Safari

### ISSUE THREAD

**Issue by sh-cho** [gmertes/NflxMultiSubs#18]
![image](https://user-images.githubusercontent.com/11611397/144074269-d91b7953-ae18-4736-84a0-a135ccf7c06f.png)
(How to get away with murder, S03E08)

It happens only on Safari. Can you check @WingCH ? 

I made this issue in this repository because [WingCH/NflxMultiSubs](https://github.com/WingCH/NflxMultiSubs) doesn't support issues.

**Comment by gmertes** [comment]
This is fixed in v2.2.8. The Safari version is still on v2.2.6 it seems. @WingCH will have to update it.

> I made this issue in this repository

That's fine 👍

**Comment by WingCH** [comment]
i will update it tonight!

**Comment by WingCH** [comment]
2.2.8 version has been release in mac app store, Thank you for your interest!

https://apps.apple.com/hk/app/nflxmultisubs/id1594059167?mt=12

**Comment by sh-cho** [comment]
👍
