### ISSUE TITLE
If it is possible to introduce a version that supports iPad‘s safari later?

### ISSUE THREAD

**Issue by AndyandAndy00** [gmertes/NflxMultiSubs#19]
Thanks for porting this extension to Safari. That’s a great extension!  I'd like to know if there will be a version to iPad in the future because I’m more used to watching videos on iPad.If this is possible technically, l will wait.

**Comment by WingCH** [comment]
good suggestion, i will try it tonight

**Comment by WingCH** [comment]
Hi, i tried to use this plugin on ipad, but there are some magical problems, the experience is not perfect, considering that most people in ipad should use the official netflix app to get the best resolution, so I will not introduce a version that supports iPad‘s safari, anyway thanks for your suggestion
