### ISSUE TITLE
Secondary sub is too small

### ISSUE THREAD

**Issue by lapo-luchini** [gmertes/NflxMultiSubs#21]
This on latest Firefox on Windows10:

<img width="915" alt="image" src="https://user-images.githubusercontent.com/420454/160998118-d1da68cf-a4e3-4191-b937-ee859c56b99e.png">

**Comment by lapo-luchini** [comment]
Yes, it does change with the 5 values (and the base sub does too)… but (as shown) they all are smaller.
<img width="916" alt="image" src="https://user-images.githubusercontent.com/420454/161065457-a8a87985-3e09-47d0-a83f-dd2a26c065a1.png">
This is [from there](https://www.netflix.com/watch/70069631?trackId=14170286), around 0:59.

**Comment by lapo-luchini** [comment]
Primary:
```HTML
<div class="nflxmultisubs-primary-wrapper" style="position: absolute; width: 100%; height: 100%; top: 0px; left: 0px;">
    <style>.player-timedtext-text-container span {
    font-size: 25.5px !important;
    opacity: 1;
  }.player-timedtext-text-container span {
    font-size: 25.5px !important;
    opacity: 1;
  }

  .player-timedtext-text-container {
    top: 517.7666717529297px !important;
    left: 465.9916687011719px !important;
  }</style>
    <div class="player-timedtext" style="position: absolute; inset: 127px 0px; display: block; direction: ltr;">
        <div style="display: block; white-space: nowrap; text-align: center; position: absolute; left: 38.1967%; bottom: 10%;" class="player-timedtext-text-container">
            <span style="font-size:30px;line-height:normal;font-weight:normal;font-style:italic;color:#00ffff;text-shadow:#000000 0px 0px 7px;font-family:Netflix Sans,Helvetica Nueue,Helvetica,Arial,sans-serif;font-weight:bolder">Oggi, in pausa pranzo,</span>
            <span style="font-size:30px;line-height:normal;font-weight:normal;font-style:italic;color:#00ffff;text-shadow:#000000 0px 0px 7px;font-family:Netflix Sans,Helvetica Nueue,Helvetica,Arial,sans-serif;font-weight:bolder">
                <br>sfideremo i magazzinieri</span>
            </div>
        </div>
    </div>
```
and secondary:
```HTML
<div class="nflxmultisubs-subtitle-wrapper" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; z-index: 2; display: flex; align-items: center;">
    <div class="nflxmultisubs-subtitle-container" style="position: relative; width: 100%; max-height: 100%;">
        <svg class="nflxmultisubs-subtitle-svg" style="position: absolute; width: 100%; inset: 0px;" width="100%" height="100%" viewBox="0 0 1220 940">
            <text text-anchor="middle" alignment-baseline="hanging" dominant-baseline="hanging" paint-order="stroke" stroke="black" stroke-width="2px" x="610" y="808.4" opacity="1" style="font-size: 29.3399px; font-family: Arial, Helvetica; fill: white; stroke: black;">we are going to be playing 
the warehouse staff </text>
        </svg>
        <div class="nflxmultisubs-subtitle-padding" style="display: block; content: &quot; &quot;; width: 100%; padding-top: 56.25%;"></div>
    </div>
</div>
```

**Comment by gmertes** [comment]
Not able to reproduce it on my end with The Office, secondary subs are much bigger for me :( You could try checking if it is maybe related to your device settings. Do you have some kind of DPI scaling turned on, or is your browser window zoomed in/out by any chance? 

I'll be traveling from tomorrow with limited internet access for about 2 weeks, I'll be able to investigate more once I get back.

**Comment by lapo-luchini** [comment]
No zooming in Firefox, but screen is HiDPI:
<img width="253" alt="image" src="https://user-images.githubusercontent.com/420454/161139647-634f53e9-774c-4d07-961f-891e5063f9c2.png">
As far as the CSS goes I see `font-size:30px` for primary and `font-size:29.3399px` for secondary… I guess there's some other scaling involved.

> I'll be traveling from tomorrow with limited internet access for about 2 weeks, I'll be able to investigate more once I get back.

No problems, I'll take a look myself in the meantime.

**Comment by gmertes** [comment]
Sorry for the long wait. Yep, was able to reproduce this by emulating your 4K display with the Chrome dev tools. Font size is scaled relative to the display width according to a magic formula (code [here](https://github.com/gmertes/NflxMultiSubs/blob/2cd07010e7e02a0a66d7f3271551c68b7f5041bc/src/nflxmultisubs.js#L252)), and evidently it doesn't work well for higher resolutions. I'll see if I can come up with a better scaling solution.

**Comment by gmertes** [comment]
@lapo-luchini I created a test release [v2.2.10-alpha](https://github.com/gmertes/NflxMultiSubs/releases/tag/v2.2.10-alpha). Could you try it out and see if the scaling is better now? 

I used a much more straightforward [scaling formula](https://github.com/gmertes/NflxMultiSubs/commit/56e4f6d45d267f534d871b2570e6b43a38876652#diff-5867324082b27a36b2de17344d633bc5db22611f8dab0d9746d6fa2320550c1aR253): simply divide the display height by 30. This seems to give more consistent scaling across resolutions. I also increased the scaling factor for the largest font size a little bit.

**Comment by lapo-luchini** [comment]
Hi! I tried… this happens though:
<img width="291" alt="image" src="https://user-images.githubusercontent.com/420454/168494068-d2a747bc-a661-439d-86b3-2f36b11ed54f.png">

**Comment by gmertes** [comment]
@lapo-luchini Did you choose the correct version (firefox) ? Anyway, I already merged the new scaling formula in the latest release (v2.2.10). Could you install/update from the [addon store](https://addons.mozilla.org/en-GB/firefox/addon/nflxmultisubs-2021/) and see if it's better now?
