### ISSUE TITLE
插件用不了

### ISSUE THREAD

**Issue by sexeros** [gmertes/NflxMultiSubs#30]
![image](https://user-images.githubusercontent.com/47104560/177612999-a71bb846-bd74-4a4a-b025-28c601a4afc6.png)
还是不显示

**Comment by gmertes** [comment]
Unable to reproduce, it works on my end. Have you tried a simple refresh?

1. Which browser?
2. Are you sure you're on the latest version v2.3.0?
3. Please copy paste the console log here (ctrl+shift+J -> console)

**Comment by sexeros** [comment]
> ![image](https://user-images.githubusercontent.com/47104560/177612999-a71bb846-bd74-4a4a-b025-28c601a4afc6.png) 还是不显示
