### ISSUE TITLE
Support for show/hide all subtitles with keyboard shortcut

### ISSUE THREAD

**Issue by yakirbit** [gmertes/NflxMultiSubs#32]
Can you add this this feature please:
Option for configuration of keyboard shortcut to show and hide all the subtitles at once on the screen.

Thanks in advance.

**Comment by gmertes** [comment]
Thanks for the suggestion @yakirbit. I don't have any plans to expand the options page to make this a configurable option. But I'm not opposed to just hard-code a key. VLC has `v` to show/hide subtitles, what do you think?
