### ISSUE TITLE
Change Speed Shortcut 

### ISSUE THREAD

**Issue by HalBenHB** [gmertes/NflxMultiSubs#40]
I'm using your Chrome extension and have a [Turkish Q Keyboard](http://kbdlayout.info/KBDTUQ/). So, I need to press "ğ" and "ü" to change speed. I want to control it via my mouse. I checked your code and what the extension actually waits is KeyCode.219 and KeyCode.221. I want to key these codes to my mouse by AutoHotkey and X-Mouse Button Control, but cannot. I would really like to see a way to remap these keys from your plugin.

**Comment by gmertes** [comment]
@HalBenHB Thanks for the suggestion, but I don't have any immediate plans to make the keys configurable.

> AutoHotkey and X-Mouse Button Control

In principle you should be able to achieve what you want to do with these. Is the problem that you're unable to map the Turkish ğ and ü to a button on the mouse? Are you able to bind the keys [ and ] to a mouse button? Those are the intended keybinds, but the deprecated KeyCode API seems to be mapping it to ğ and ü. If you're able to use [ and ], I should be able to fix it.

**Comment by gmertes** [comment]
@HalBenHB 

I updated the keyboard event handler so that it now listens to both the physical keys and the character values. So in your case, the playback controller will work with both `ğ`/`ü` and `[`/`]`. 

I created a test release here: https://github.com/gmertes/NflxMultiSubs/releases/tag/v2.3.4-alpha

Can you test this for me? Download the zip for chrome or firefox from the release page. You can follow the install instructions [here](https://github.com/gmertes/NflxMultiSubs/blob/master/INSTALL.md) (click on manual install at the bottom). If you bind the keys `[` and `]` on your mouse it should work now.

**Comment by HalBenHB** [comment]
I uninstall current version from my Chrome and installed your test release. It gives this error "Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details."

![image](https://user-images.githubusercontent.com/53787826/220931578-72bbe809-a479-4e5a-8a07-736b37875b27.png)
![image](https://user-images.githubusercontent.com/53787826/220931520-7b972550-07ee-4354-b718-c83ad3d7dc10.png)

However, it works on Netflix by "ğ" and "ü" on my keyboard. Also, it now supports X-Mouse Button Control when I remap "[" and "]" (not ğ and ü)

![image](https://user-images.githubusercontent.com/53787826/220929993-51fb950f-546e-47a8-bb78-a42e4ba8d85f.png)

For your notice, I double checked with these programs before uninstall the current version. X-Mouse Button Control didn't work  again for both "ğ/ü" or "[ / ]". However, remapping "ğ/ü" worked fine with AutoHotkey.
`#IfWinActive Netflix
XButton1::ğ
XButton2::ü`

Still, I will continue from your test version because I don't want to run an AutoHotkey script. XMBC is always on and it automatically change its mapping when I'm on a Window called Netflix. So, thanks for your update.

**Comment by gmertes** [comment]
Glad to hear it works now, and thanks for testing! That manifest error is normal.

I will push this release (v2.3.4) to the store soon, when that's done I suggest to uninstall the test version and install from the Chrome store again so that you get automatic updates in the future.
