### ISSUE TITLE
License error

### ISSUE THREAD

**Issue by Seby68** [gmertes/NflxMultiSubs#43]
https://github.com/nodeca/pako/blob/main/LICENSE
Hello, I wanted to let you know that the URL of this license is not right, there is probably an error or it has been changed.

**Comment by gmertes** [comment]
The license file is automatically generated by webpack, which in turn gets it from the dependencies. Nothing I can do about it from my end. That particular link is imported from JSZip, so you could open an issue in their repository (but it's really not that important tbh).
