### ISSUE TITLE
次字幕字体大小问题 (Subtitle font size issue)

### ISSUE THREAD

**Issue by chenzhihao1040728129** [gmertes/NflxMultiSubs#45]
1
first thanks author:
Subtitle font size issue,
I selected the maximum, but the two subtitles are not the same size
![image](https://github.com/gmertes/NflxMultiSubs/assets/49114216/8e5a70fd-85cb-456c-a8e5-9d1aea03c8ad)

1

**Comment by gmertes** [comment]
Hi, thanks for the report! Could you tell me your browser and screen resolution? And just to confirm: the size setting does work? 

I will look into improving it, it has been on my todo list for a while. Maybe make it a slider or an input box so you can choose the exact size you want.

**Comment by chenzhihao1040728129** [comment]
> Hi, thanks for the report! Could you tell me your browser and screen resolution? And just to confirm: the size setting does work?您好，感谢您的报告！您能告诉我您的浏览器和屏幕分辨率吗？只是为了确认：尺寸设置是否有效？
> 
> I will look into improving it, it has been on my todo list for a while. Maybe make it a slider or an input box so you can choose the exact size you want.我会考虑改进它，它已经在我的待办事项清单上有一段时间了。也许将其设置为滑块或输入框，以便您可以选择所需的确切尺寸。

Chrome   ,     1920 X 1080

**Comment by gmertes** [comment]
Sorry for the long wait. I reworked the font size settings in the latest version (v.2.3.5). You should now be able to increase the font size more. Could you check if this solves your issue?

**Comment by chenzhihao1040728129** [comment]
yes, the require is solve, thanks author

**Comment by chenzhihao1040728129** [comment]
> Sorry for the long wait. I reworked the font size settings in the latest version (v.2.3.5). You should now be able to increase the font size more. Could you check if this solves your issue?抱歉让您久等了。我在最新版本（v.2.3.5）中重新设计了字体大小设置。您现在应该能够进一步增加字体大小。您能检查一下这是否解决了您的问题吗？

yes, the require is solve, thanks author
