### ISSUE TITLE
[Firefox] [Bug] Playback speed changes inadvertently when keyboard shortcuts are used

### ISSUE THREAD

**Issue by sloria** [gmertes/NflxMultiSubs#52]
Version: 2.3.5
Browser: Firefox 126.0.1 
OS: macOS 14.5

While viewing videos with primary and secondary subtitles enabled, the playback speed speeds up at seemingly random times to ~1.2x, without any user interaction. I've observed this on multiple videos.

**Comment by sloria** [comment]
Actually, I think what might be happening is that the `[`/`]` shortcut is being triggered even when other shortcuts are used. I use cmd+shift+] to switch to the next tab, and this inadvertently triggers this extension to increase the speed.

Ideally, the shortcut should only be triggered when `]` is pressed on its own within the netflix tab. In the meantime, is there a way to disable this keyboard shortcut?

**Comment by gmertes** [comment]
Thanks for the report! Unless you modify the code and build the extension locally, there's no way to disable the shortcut.

But I will fix it, I forgot to check modifier keys. Expect a new version with the fix in the next couple days.

**Comment by sloria** [comment]
Thank you!

**Comment by gmertes** [comment]
Fixed in v2.3.6
