### ISSUE TITLE
Subtitles Overlapping issues.

### ISSUE THREAD

**Issue by abhigarg-iitk** [gmertes/NflxMultiSubs#9]
I think the extension has an issue where 

(1) multiline subtitles get overlapped. And 

(2) Primary image-based subtitles does not get scaled properly. (I think the div name for image-based subtitles was changed from `image-based-timed-text` to `image-based-subtitles`)

**Comment by gmertes** [comment]
Great! I'll have an official release out soon. For now you can keep using the alpha release.
